### ISSUE TITLE
Does config-syncer support namespace wildcard like kubernetes-reflector

### ISSUE THREAD

**Issue by shiyuhang0** [kubeops/config-syncer#530]
```
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "false"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "prod.*"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
```
